export default {
 state: {
  camps: [
    {
      campground_id: 11,
      campground_name: '小野（半岛）',
      image: require('@/assets/camp11.png'),
      introduction: '上海最美的日落营地，可体验浆板、帆船',
      city: ['上海'],
      address: '上海市青浦区金泽镇双祥村商周公路988号',
      infrastructures: ['停车场', '信号', '卫生间', '消防措施', '淋浴房'],
      campsite_number: 15,
      availabilities: ['可供电', '可拎包入住', '可携带宠物', '可明火', '可自带帐篷', '可过夜', '草地', '沙地'],
      detail_images: [require('@/assets/camp/detail/11-1.png'), require('@/assets/camp/detail/11-2.png'), require('@/assets/camp/detail/11-3.png'),],
      introduction_image: require('@/assets/camp/introduction/11.png'),
      campsite_image: require('@/assets/camp/campsite/21.png'),
      campsite_id:['A1','A2','A3','A4','A5','A6','A7',
                   'B1','B2','B3','B5',
                   'C1','C2','C3']

    },
    {
      campground_id: 21,
      campground_name: '竹野公园',
      image: require('@/assets/camp21.png'),
      introduction: '竹林环绕的静谧之所',
      city: ['绍兴'],
      address: '上海市青浦区金泽镇双祥村商周公路988号',
      infrastructures: ['停车场', '信号', '卫生间', '消防措施', '淋浴房'],
      campsite_number: 15,
      availabilities: ['可供电', '可拎包入住', '可携带宠物', '可明火', '可自带帐篷', '可过夜', '草地', '沙地'],
      detail_images: [require('@/assets/camp/detail/11-1.png'), require('@/assets/camp/detail/11-2.png'), require('@/assets/camp/detail/11-3.png'),],
      introduction_image: require('@/assets/camp/introduction/11.png'),
      campsite_image: require('@/assets/camp/campsite/21.png'),
      campsite_id:['A1','A2','A3','A4','A5','A6','A7',
        'B1','B2','B3','B5',
        'C1','C2','C3']
    },
    {
      campground_id: 22,
      campground_name: '诸暨红枫岭营地',
      image: require('@/assets/camp22.png'),
      introduction: '藏在五泄森林中的法式小清新',
      city: ['绍兴'],
      address: '上海市青浦区金泽镇双祥村商周公路988号',
      infrastructures: ['停车场', '信号', '卫生间', '消防措施', '淋浴房'],
      campsite_number: 15,
      availabilities: ['可供电', '可拎包入住', '可携带宠物', '可明火', '可自带帐篷', '可过夜', '草地', '沙地'],
      detail_images: [require('@/assets/camp/detail/11-1.png'), require('@/assets/camp/detail/11-2.png'), require('@/assets/camp/detail/11-3.png'),],
      introduction_image: require('@/assets/camp/introduction/11.png'),
      campsite_image: require('@/assets/camp/campsite/21.png'),
      campsite_id:['A1','A2','A3','A4','A5','A6','A7',
        'B1','B2','B3','B5',
        'C1','C2','C3']
    },
    {
      campground_id: 31,
      campground_name: '小野（森谷）',
      image: require('@/assets/camp31.png'),
      introduction: '林间山野，溪流石苔',
      city: ['桐庐'],
      address: '上海市青浦区金泽镇双祥村商周公路988号',
      infrastructures: ['停车场', '信号', '卫生间', '消防措施', '淋浴房'],
      campsite_number: 15,
      availabilities: ['可供电', '可拎包入住', '可携带宠物', '可明火', '可自带帐篷', '可过夜', '草地', '沙地'],
      detail_images: [require('@/assets/camp/detail/11-1.png'), require('@/assets/camp/detail/11-2.png'), require('@/assets/camp/detail/11-3.png'),],
      introduction_image: require('@/assets/camp/introduction/11.png'),
      campsite_image: require('@/assets/camp/campsite/21.png'),
      campsite_id:['A1','A2','A3','A4','A5','A6','A7',
        'B1','B2','B3','B5',
        'C1','C2','C3']
    },
    {
      campground_id: 41,
      campground_name: '小野（杭州）',
      image: require('@/assets/camp41.png'),
      introduction: '不设限的城市乌托邦',
      city: ['杭州'],
      address: '上海市青浦区金泽镇双祥村商周公路988号',
      infrastructures: ['停车场', '信号', '卫生间', '消防措施', '淋浴房'],
      campsite_number: 15,
      availabilities: ['可供电', '可拎包入住', '可携带宠物', '可明火', '可自带帐篷', '可过夜', '草地', '沙地'],
      detail_images: [require('@/assets/camp/detail/11-1.png'), require('@/assets/camp/detail/11-2.png'), require('@/assets/camp/detail/11-3.png'),],
      introduction_image: require('@/assets/camp/introduction/11.png'),
      campsite_image: require('@/assets/camp/campsite/21.png'),
      campsite_id:['A1','A2','A3','A4','A5','A6','A7',
        'B1','B2','B3','B5',
        'C1','C2','C3']
    },
    {
      campground_id: 51,
      campground_name: '小野（松屿）',
      image: require('@/assets/camp51.png'),
      introduction: '与湖景相伴，与松林为伍，全景观营地',
      city: ['湖州'],
      address: '上海市青浦区金泽镇双祥村商周公路988号',
      infrastructures: ['停车场', '信号', '卫生间', '消防措施', '淋浴房'],
      campsite_number: 15,
      availabilities: ['可供电', '可拎包入住', '可携带宠物', '可明火', '可自带帐篷', '可过夜', '草地', '沙地'],
      detail_images: [require('@/assets/camp/detail/11-1.png'), require('@/assets/camp/detail/11-2.png'), require('@/assets/camp/detail/11-3.png'),],
      introduction_image: require('@/assets/camp/introduction/11.png'),
      campsite_image: require('@/assets/camp/campsite/21.png'),
      campsite_id:['A1','A2','A3','A4','A5','A6','A7',
        'B1','B2','B3','B5',
        'C1','C2','C3']
    },
    {
      campground_id: 52,
      campground_name: '小野（莫干山）',
      image: require('@/assets/camp52.png'),
      introduction: '抹茶千层味的山顶营地，晨起看云雾，黄昏有夕阳',
      city: ['湖州'],
      address: '上海市青浦区金泽镇双祥村商周公路988号',
      infrastructures: ['停车场', '信号', '卫生间', '消防措施', '淋浴房'],
      campsite_number: 15,
      availabilities: ['可供电', '可拎包入住', '可携带宠物', '可明火', '可自带帐篷', '可过夜', '草地', '沙地'],
      detail_images: [require('@/assets/camp/detail/11-1.png'), require('@/assets/camp/detail/11-2.png'), require('@/assets/camp/detail/11-3.png'),],
      introduction_image: require('@/assets/camp/introduction/11.png'),
      campsite_image: require('@/assets/camp/campsite/21.png'),
      campsite_id:['A1','A2','A3','A4','A5','A6','A7',
        'B1','B2','B3','B5',
        'C1','C2','C3']
    },
    
  ]
  }
}